contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #snrnaseq channel"
    url: https://nfcore.slack.com/channels/snrnaseq
    about: Discussion about the nf-core/snrnaseq pipeline
